name: CustomPrefix
main: com.blalp.custompref.CustomPrefix
version: 1.1
depend: [Vault]

commands:
  prefix:
   aliases: [pre]
   description: Allows players to request a prefix
  prefixpending:
   aliases: [adminpre,adminprefix,adpre,adprefix]
   description: Allows managers to approve prefixes.
  prefixadmin:
   aliases: []
   description: Allows admins to request prefix for other people.
